name = "finance-app-nextjs"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[services]
[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "finance-app-nextjs"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "finance-app-nextjs-bucket"
