import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import getServerDarkMode from "@/hooks/get-server-dark-mode";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
    title: {
        template: "%s | Finance App",
        default: "Finance App"
    },
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const theme = getServerDarkMode()
  return (
      <html lang="en" className={theme}>
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      {children}
      </body>
      </html>
  );
}
