import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {UserProvider} from "@/lib/use-user";
import {userDefaults} from "@/lib/user-defaults";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
    title: {
        template: "%s | Finance App",
        default: "Finance App"
    },
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const theme = userDefaults.theme;
    return (
        <UserProvider>
            <html lang="en" className={theme}>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            {children}
            </body>
            </html>
        </UserProvider>
    );
}
